
server:
  port: 9000

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/lucassousa
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: event-api
          uri: http://localhost:8082
          predicates:
            - Path=/event-plans/**, /events/**, /event-registrations/**, /activities/**, /activity-registrations/**, /attendance/**
          filters:
            - TokenRelay=
          metadata:
            cors:
              allowedOrigins: "http://localhost:3000"  # URL do frontend
              allowedMethods: "GET, POST, PUT, DELETE"
              allowedHeaders: "*"
              allowCredentials: true
